### ISSUE TITLE
Issue with package installing with Pycharm

### ISSUE THREAD

**Issue by Hskyeye** [ardiloot/NonlinearTMM#1]
Python 3.6; All the required other packages are updated using Pycharm.

pip install NonlinearTMM==1.3.3
error occured:

NonlinearTMM/src/eigen_3.3.2/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]

Not sure how to solve this issue. Thanks!

**Comment by ardiloot** [comment]
Could you specify your system specs like OS version, python version 32/64 bit, C++ compiler version?

**Comment by Hskyeye** [comment]
Here is some more information, not sure if it will be helpful for solving my issue:

%%%%%%%%%%%%%%%%%%%%
In file included from NonlinearTMM/src/SecondOrderNLTMM.cpp:588:
  In file included from NonlinearTMM/src/NonlinearTMMCpp/NonlinearTMMCpp/Common.h:8:
  In file included from NonlinearTMM/src/eigen_3.3.2/unsupported/Eigen/CXX11/Tensor:142:
  NonlinearTMM/src/eigen_3.3.2/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
  class TensorStorage<T, FixedDimensions, Options_>
        ^
  NonlinearTMM/src/eigen_3.3.2/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: template is declared here
  template<typename T, typename Dimensions, int Options_> class TensorStorage;
                                                                ^
  In file included from NonlinearTMM/src/SecondOrderNLTMM.cpp:588:
  NonlinearTMM/src/NonlinearTMMCpp/NonlinearTMMCpp/Common.h:136:2: error: unknown type name '__forceinline'
          __forceinline dcomplex FastExp(dcomplex z) {
          ^
  NonlinearTMM/src/NonlinearTMMCpp/NonlinearTMMCpp/Common.h:136:24: error: expected ';' after top level declarator
          __forceinline dcomplex FastExp(dcomplex z) {
                                ^
                                ;
  In file included from NonlinearTMM/src/SecondOrderNLTMM.cpp:593:
  NonlinearTMM/src/NonlinearTMMCpp/NonlinearTMMCpp/SecondOrderNLTMM.h:28:26: error: unknown type name 'SecondOrderNLTMM'
                  void SetValues(int nr, SecondOrderNLTMM &tmm);
                                         ^
  NonlinearTMM/src/NonlinearTMMCpp/NonlinearTMMCpp/SecondOrderNLTMM.h:42:26: error: unknown type name 'SecondOrderNLTMM'
                  void SetValues(int nr, SecondOrderNLTMM &tmm);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Thanks!

**Comment by ardiloot** [comment]
I found and fixed some issues when compiled with GCC. Could you try the latest version `pip install NonlinearTMM=1.3.8`? The log file was very helpful.

**Comment by ardiloot** [comment]
Tested on OS X and additional compiler differences caused the compilation to fail. The latest version 1.3.10 should work. Tested on OS X 10.12.6, python 3.6.5 64bit. `pip install NonlinearTMM==1.3.10`
